name: Dependabot
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Dependabot
        uses: dependabot/dependabot-core@v0.161.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
